### PR TITLE
Doc remove lena

### PR DESCRIPTION
**Pull request by tacaswell**
Replaces the png logo with just text.

### CODE REVIEW

**Comment by tacaswell** [comment]
This of course breaks the pegagogy in one of the inner pages http://matplotlib.org/sampledoc/custom_look.html

**Comment by tacaswell** [comment]
ok, that is fixed now too.

**Comment by matthew-brett** [comment]
Thanks very much for doing that.   Looks good to me.

**Comment by QuLogic** [comment]
The screenshot doesn't seem as _fancy_ as it did before (logo notwithstanding); is it really using the custom CSS that the text suggests?

**Comment by tacaswell** [comment]
Good catch, I also changed the `conf.py` to make it look right which seems to be what is controlling this now.

The posted site was built with sphinx 1.1.3, I am testing with sphinx 1.3.1.  I wonder if sphinx has moved under us?

I am inclined to

**Pull request merged**
