### PR TITLE
Updating Getting Started and Customizing the look and feel.

### PR DESCRIPTION
**Pull request by biophyser**
I added a line in custom_look to change the html theme to address the root cause of issue #16. I also updated the screenshots on the getting_started and custom_look pages. Also got a doctest error caused by #20 so I changed it back to get the build to work.

### CODE REVIEW

**Comment by phobson** [comment]
Thanks for the PR. Rather than creating new files ("new_basic_screenshot") can you just rewrite the old files? They won't be "new" for very long.

**Comment by biophyser** [comment]
Sorry, missed that one.

**Comment by tacaswell** [comment]
@biophyser what version of numpy are you using?  The change to the spacing in reprs is a change in a recent version of numpy, would rather leave it to pass with newer version rather than old.

**Comment by tacaswell** [comment]
@biophyser Sorry, I did not follow your last comment all the way.  I am correct that the way it is now (no change) works with np.1.14?

**Comment by biophyser** [comment]
Sorry for the confusion @tacaswell. The changes I originally made worked with np 1.13 but not with np 1.14. I pushed a commit earlier today that reversed the changes in the `ipython_directive` file so it is compatible with np 1.14 now.

**Comment by tacaswell** [comment]
Thanks @biophyser !

**Pull request merged**
